// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: storageserver.proto
#ifndef GRPC_storageserver_2eproto__INCLUDED
#define GRPC_storageserver_2eproto__INCLUDED

#include "storageserver.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace storageserver {

// The greeting service definition.
class Storage final {
 public:
  static constexpr char const* service_full_name() {
    return "storageserver.Storage";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status SayHello(::grpc::ClientContext* context, const ::storageserver::HelloRequest& request, ::storageserver::HelloReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::storageserver::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::storageserver::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    // Send meta data
    virtual ::grpc::Status FileOpen(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::storageserver::FileMetaDataReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileMetaDataReply>> AsyncFileOpen(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileMetaDataReply>>(AsyncFileOpenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileMetaDataReply>> PrepareAsyncFileOpen(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileMetaDataReply>>(PrepareAsyncFileOpenRaw(context, request, cq));
    }
    // Send data
    virtual ::grpc::Status FileWrite(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest& request, ::storageserver::FileWriteReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileWriteReply>> AsyncFileWrite(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileWriteReply>>(AsyncFileWriteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileWriteReply>> PrepareAsyncFileWrite(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileWriteReply>>(PrepareAsyncFileWriteRaw(context, request, cq));
    }
    // Close file
    virtual ::grpc::Status FileClose(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::storageserver::FileMetaDataReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileMetaDataReply>> AsyncFileClose(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileMetaDataReply>>(AsyncFileCloseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileMetaDataReply>> PrepareAsyncFileClose(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileMetaDataReply>>(PrepareAsyncFileCloseRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a greeting
      virtual void SayHello(::grpc::ClientContext* context, const ::storageserver::HelloRequest* request, ::storageserver::HelloReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SayHello(::grpc::ClientContext* context, const ::storageserver::HelloRequest* request, ::storageserver::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Send meta data
      virtual void FileOpen(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest* request, ::storageserver::FileMetaDataReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FileOpen(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest* request, ::storageserver::FileMetaDataReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Send data
      virtual void FileWrite(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest* request, ::storageserver::FileWriteReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FileWrite(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest* request, ::storageserver::FileWriteReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Close file
      virtual void FileClose(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest* request, ::storageserver::FileMetaDataReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FileClose(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest* request, ::storageserver::FileMetaDataReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::storageserver::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::storageserver::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileMetaDataReply>* AsyncFileOpenRaw(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileMetaDataReply>* PrepareAsyncFileOpenRaw(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileWriteReply>* AsyncFileWriteRaw(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileWriteReply>* PrepareAsyncFileWriteRaw(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileMetaDataReply>* AsyncFileCloseRaw(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::storageserver::FileMetaDataReply>* PrepareAsyncFileCloseRaw(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SayHello(::grpc::ClientContext* context, const ::storageserver::HelloRequest& request, ::storageserver::HelloReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::storageserver::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::storageserver::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
    ::grpc::Status FileOpen(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::storageserver::FileMetaDataReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::FileMetaDataReply>> AsyncFileOpen(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::FileMetaDataReply>>(AsyncFileOpenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::FileMetaDataReply>> PrepareAsyncFileOpen(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::FileMetaDataReply>>(PrepareAsyncFileOpenRaw(context, request, cq));
    }
    ::grpc::Status FileWrite(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest& request, ::storageserver::FileWriteReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::FileWriteReply>> AsyncFileWrite(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::FileWriteReply>>(AsyncFileWriteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::FileWriteReply>> PrepareAsyncFileWrite(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::FileWriteReply>>(PrepareAsyncFileWriteRaw(context, request, cq));
    }
    ::grpc::Status FileClose(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::storageserver::FileMetaDataReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::FileMetaDataReply>> AsyncFileClose(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::FileMetaDataReply>>(AsyncFileCloseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::FileMetaDataReply>> PrepareAsyncFileClose(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::storageserver::FileMetaDataReply>>(PrepareAsyncFileCloseRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SayHello(::grpc::ClientContext* context, const ::storageserver::HelloRequest* request, ::storageserver::HelloReply* response, std::function<void(::grpc::Status)>) override;
      void SayHello(::grpc::ClientContext* context, const ::storageserver::HelloRequest* request, ::storageserver::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FileOpen(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest* request, ::storageserver::FileMetaDataReply* response, std::function<void(::grpc::Status)>) override;
      void FileOpen(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest* request, ::storageserver::FileMetaDataReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FileWrite(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest* request, ::storageserver::FileWriteReply* response, std::function<void(::grpc::Status)>) override;
      void FileWrite(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest* request, ::storageserver::FileWriteReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FileClose(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest* request, ::storageserver::FileMetaDataReply* response, std::function<void(::grpc::Status)>) override;
      void FileClose(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest* request, ::storageserver::FileMetaDataReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::storageserver::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::storageserver::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storageserver::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::storageserver::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storageserver::FileMetaDataReply>* AsyncFileOpenRaw(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storageserver::FileMetaDataReply>* PrepareAsyncFileOpenRaw(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storageserver::FileWriteReply>* AsyncFileWriteRaw(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storageserver::FileWriteReply>* PrepareAsyncFileWriteRaw(::grpc::ClientContext* context, const ::storageserver::FileWriteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storageserver::FileMetaDataReply>* AsyncFileCloseRaw(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::storageserver::FileMetaDataReply>* PrepareAsyncFileCloseRaw(::grpc::ClientContext* context, const ::storageserver::FileMetaDataRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHello_;
    const ::grpc::internal::RpcMethod rpcmethod_FileOpen_;
    const ::grpc::internal::RpcMethod rpcmethod_FileWrite_;
    const ::grpc::internal::RpcMethod rpcmethod_FileClose_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::storageserver::HelloRequest* request, ::storageserver::HelloReply* response);
    // Send meta data
    virtual ::grpc::Status FileOpen(::grpc::ServerContext* context, const ::storageserver::FileMetaDataRequest* request, ::storageserver::FileMetaDataReply* response);
    // Send data
    virtual ::grpc::Status FileWrite(::grpc::ServerContext* context, const ::storageserver::FileWriteRequest* request, ::storageserver::FileWriteReply* response);
    // Close file
    virtual ::grpc::Status FileClose(::grpc::ServerContext* context, const ::storageserver::FileMetaDataRequest* request, ::storageserver::FileMetaDataReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::storageserver::HelloRequest* /*request*/, ::storageserver::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::storageserver::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::storageserver::HelloReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FileOpen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FileOpen() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_FileOpen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileOpen(::grpc::ServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFileOpen(::grpc::ServerContext* context, ::storageserver::FileMetaDataRequest* request, ::grpc::ServerAsyncResponseWriter< ::storageserver::FileMetaDataReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FileWrite : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FileWrite() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_FileWrite() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileWrite(::grpc::ServerContext* /*context*/, const ::storageserver::FileWriteRequest* /*request*/, ::storageserver::FileWriteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFileWrite(::grpc::ServerContext* context, ::storageserver::FileWriteRequest* request, ::grpc::ServerAsyncResponseWriter< ::storageserver::FileWriteReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FileClose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FileClose() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_FileClose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileClose(::grpc::ServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFileClose(::grpc::ServerContext* context, ::storageserver::FileMetaDataRequest* request, ::grpc::ServerAsyncResponseWriter< ::storageserver::FileMetaDataReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<WithAsyncMethod_FileOpen<WithAsyncMethod_FileWrite<WithAsyncMethod_FileClose<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::storageserver::HelloRequest, ::storageserver::HelloReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::storageserver::HelloRequest* request, ::storageserver::HelloReply* response) { return this->SayHello(context, request, response); }));}
    void SetMessageAllocatorFor_SayHello(
        ::grpc::MessageAllocator< ::storageserver::HelloRequest, ::storageserver::HelloReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::storageserver::HelloRequest, ::storageserver::HelloReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::storageserver::HelloRequest* /*request*/, ::storageserver::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::storageserver::HelloRequest* /*request*/, ::storageserver::HelloReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FileOpen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FileOpen() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::storageserver::FileMetaDataRequest, ::storageserver::FileMetaDataReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::storageserver::FileMetaDataRequest* request, ::storageserver::FileMetaDataReply* response) { return this->FileOpen(context, request, response); }));}
    void SetMessageAllocatorFor_FileOpen(
        ::grpc::MessageAllocator< ::storageserver::FileMetaDataRequest, ::storageserver::FileMetaDataReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::storageserver::FileMetaDataRequest, ::storageserver::FileMetaDataReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FileOpen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileOpen(::grpc::ServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FileOpen(
      ::grpc::CallbackServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FileWrite : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FileWrite() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::storageserver::FileWriteRequest, ::storageserver::FileWriteReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::storageserver::FileWriteRequest* request, ::storageserver::FileWriteReply* response) { return this->FileWrite(context, request, response); }));}
    void SetMessageAllocatorFor_FileWrite(
        ::grpc::MessageAllocator< ::storageserver::FileWriteRequest, ::storageserver::FileWriteReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::storageserver::FileWriteRequest, ::storageserver::FileWriteReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FileWrite() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileWrite(::grpc::ServerContext* /*context*/, const ::storageserver::FileWriteRequest* /*request*/, ::storageserver::FileWriteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FileWrite(
      ::grpc::CallbackServerContext* /*context*/, const ::storageserver::FileWriteRequest* /*request*/, ::storageserver::FileWriteReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FileClose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FileClose() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::storageserver::FileMetaDataRequest, ::storageserver::FileMetaDataReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::storageserver::FileMetaDataRequest* request, ::storageserver::FileMetaDataReply* response) { return this->FileClose(context, request, response); }));}
    void SetMessageAllocatorFor_FileClose(
        ::grpc::MessageAllocator< ::storageserver::FileMetaDataRequest, ::storageserver::FileMetaDataReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::storageserver::FileMetaDataRequest, ::storageserver::FileMetaDataReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FileClose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileClose(::grpc::ServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FileClose(
      ::grpc::CallbackServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SayHello<WithCallbackMethod_FileOpen<WithCallbackMethod_FileWrite<WithCallbackMethod_FileClose<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::storageserver::HelloRequest* /*request*/, ::storageserver::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FileOpen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FileOpen() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_FileOpen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileOpen(::grpc::ServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FileWrite : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FileWrite() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_FileWrite() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileWrite(::grpc::ServerContext* /*context*/, const ::storageserver::FileWriteRequest* /*request*/, ::storageserver::FileWriteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FileClose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FileClose() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_FileClose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileClose(::grpc::ServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SayHello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::storageserver::HelloRequest* /*request*/, ::storageserver::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FileOpen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FileOpen() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_FileOpen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileOpen(::grpc::ServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFileOpen(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FileWrite : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FileWrite() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_FileWrite() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileWrite(::grpc::ServerContext* /*context*/, const ::storageserver::FileWriteRequest* /*request*/, ::storageserver::FileWriteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFileWrite(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FileClose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FileClose() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_FileClose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileClose(::grpc::ServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFileClose(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SayHello() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SayHello(context, request, response); }));
    }
    ~WithRawCallbackMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::storageserver::HelloRequest* /*request*/, ::storageserver::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SayHello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FileOpen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FileOpen() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FileOpen(context, request, response); }));
    }
    ~WithRawCallbackMethod_FileOpen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileOpen(::grpc::ServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FileOpen(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FileWrite : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FileWrite() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FileWrite(context, request, response); }));
    }
    ~WithRawCallbackMethod_FileWrite() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileWrite(::grpc::ServerContext* /*context*/, const ::storageserver::FileWriteRequest* /*request*/, ::storageserver::FileWriteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FileWrite(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FileClose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FileClose() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FileClose(context, request, response); }));
    }
    ~WithRawCallbackMethod_FileClose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileClose(::grpc::ServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FileClose(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SayHello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::storageserver::HelloRequest, ::storageserver::HelloReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::storageserver::HelloRequest, ::storageserver::HelloReply>* streamer) {
                       return this->StreamedSayHello(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* /*context*/, const ::storageserver::HelloRequest* /*request*/, ::storageserver::HelloReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSayHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::storageserver::HelloRequest,::storageserver::HelloReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FileOpen : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FileOpen() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::storageserver::FileMetaDataRequest, ::storageserver::FileMetaDataReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::storageserver::FileMetaDataRequest, ::storageserver::FileMetaDataReply>* streamer) {
                       return this->StreamedFileOpen(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FileOpen() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FileOpen(::grpc::ServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFileOpen(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::storageserver::FileMetaDataRequest,::storageserver::FileMetaDataReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FileWrite : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FileWrite() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::storageserver::FileWriteRequest, ::storageserver::FileWriteReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::storageserver::FileWriteRequest, ::storageserver::FileWriteReply>* streamer) {
                       return this->StreamedFileWrite(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FileWrite() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FileWrite(::grpc::ServerContext* /*context*/, const ::storageserver::FileWriteRequest* /*request*/, ::storageserver::FileWriteReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFileWrite(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::storageserver::FileWriteRequest,::storageserver::FileWriteReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FileClose : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FileClose() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::storageserver::FileMetaDataRequest, ::storageserver::FileMetaDataReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::storageserver::FileMetaDataRequest, ::storageserver::FileMetaDataReply>* streamer) {
                       return this->StreamedFileClose(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FileClose() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FileClose(::grpc::ServerContext* /*context*/, const ::storageserver::FileMetaDataRequest* /*request*/, ::storageserver::FileMetaDataReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFileClose(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::storageserver::FileMetaDataRequest,::storageserver::FileMetaDataReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SayHello<WithStreamedUnaryMethod_FileOpen<WithStreamedUnaryMethod_FileWrite<WithStreamedUnaryMethod_FileClose<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SayHello<WithStreamedUnaryMethod_FileOpen<WithStreamedUnaryMethod_FileWrite<WithStreamedUnaryMethod_FileClose<Service > > > > StreamedService;
};

}  // namespace storageserver


#endif  // GRPC_storageserver_2eproto__INCLUDED
