// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storageserver.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_storageserver_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_storageserver_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_storageserver_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_storageserver_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_storageserver_2eproto;
namespace storageserver {
class FileMetaDataReply;
struct FileMetaDataReplyDefaultTypeInternal;
extern FileMetaDataReplyDefaultTypeInternal _FileMetaDataReply_default_instance_;
class FileMetaDataRequest;
struct FileMetaDataRequestDefaultTypeInternal;
extern FileMetaDataRequestDefaultTypeInternal _FileMetaDataRequest_default_instance_;
class FileWriteReply;
struct FileWriteReplyDefaultTypeInternal;
extern FileWriteReplyDefaultTypeInternal _FileWriteReply_default_instance_;
class FileWriteRequest;
struct FileWriteRequestDefaultTypeInternal;
extern FileWriteRequestDefaultTypeInternal _FileWriteRequest_default_instance_;
class HelloReply;
struct HelloReplyDefaultTypeInternal;
extern HelloReplyDefaultTypeInternal _HelloReply_default_instance_;
class HelloRequest;
struct HelloRequestDefaultTypeInternal;
extern HelloRequestDefaultTypeInternal _HelloRequest_default_instance_;
}  // namespace storageserver
PROTOBUF_NAMESPACE_OPEN
template<> ::storageserver::FileMetaDataReply* Arena::CreateMaybeMessage<::storageserver::FileMetaDataReply>(Arena*);
template<> ::storageserver::FileMetaDataRequest* Arena::CreateMaybeMessage<::storageserver::FileMetaDataRequest>(Arena*);
template<> ::storageserver::FileWriteReply* Arena::CreateMaybeMessage<::storageserver::FileWriteReply>(Arena*);
template<> ::storageserver::FileWriteRequest* Arena::CreateMaybeMessage<::storageserver::FileWriteRequest>(Arena*);
template<> ::storageserver::HelloReply* Arena::CreateMaybeMessage<::storageserver::HelloReply>(Arena*);
template<> ::storageserver::HelloRequest* Arena::CreateMaybeMessage<::storageserver::HelloRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace storageserver {

// ===================================================================

class HelloRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:storageserver.HelloRequest) */ {
 public:
  inline HelloRequest() : HelloRequest(nullptr) {}
  ~HelloRequest() override;
  explicit PROTOBUF_CONSTEXPR HelloRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HelloRequest(const HelloRequest& from);
  HelloRequest(HelloRequest&& from) noexcept
    : HelloRequest() {
    *this = ::std::move(from);
  }

  inline HelloRequest& operator=(const HelloRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HelloRequest& operator=(HelloRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HelloRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HelloRequest* internal_default_instance() {
    return reinterpret_cast<const HelloRequest*>(
               &_HelloRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HelloRequest& a, HelloRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(HelloRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HelloRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HelloRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HelloRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HelloRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HelloRequest& from) {
    HelloRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HelloRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "storageserver.HelloRequest";
  }
  protected:
  explicit HelloRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:storageserver.HelloRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_storageserver_2eproto;
};
// -------------------------------------------------------------------

class HelloReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:storageserver.HelloReply) */ {
 public:
  inline HelloReply() : HelloReply(nullptr) {}
  ~HelloReply() override;
  explicit PROTOBUF_CONSTEXPR HelloReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HelloReply(const HelloReply& from);
  HelloReply(HelloReply&& from) noexcept
    : HelloReply() {
    *this = ::std::move(from);
  }

  inline HelloReply& operator=(const HelloReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline HelloReply& operator=(HelloReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HelloReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const HelloReply* internal_default_instance() {
    return reinterpret_cast<const HelloReply*>(
               &_HelloReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(HelloReply& a, HelloReply& b) {
    a.Swap(&b);
  }
  inline void Swap(HelloReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HelloReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HelloReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HelloReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HelloReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HelloReply& from) {
    HelloReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HelloReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "storageserver.HelloReply";
  }
  protected:
  explicit HelloReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // @@protoc_insertion_point(class_scope:storageserver.HelloReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_storageserver_2eproto;
};
// -------------------------------------------------------------------

class FileMetaDataRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:storageserver.FileMetaDataRequest) */ {
 public:
  inline FileMetaDataRequest() : FileMetaDataRequest(nullptr) {}
  ~FileMetaDataRequest() override;
  explicit PROTOBUF_CONSTEXPR FileMetaDataRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileMetaDataRequest(const FileMetaDataRequest& from);
  FileMetaDataRequest(FileMetaDataRequest&& from) noexcept
    : FileMetaDataRequest() {
    *this = ::std::move(from);
  }

  inline FileMetaDataRequest& operator=(const FileMetaDataRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileMetaDataRequest& operator=(FileMetaDataRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileMetaDataRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileMetaDataRequest* internal_default_instance() {
    return reinterpret_cast<const FileMetaDataRequest*>(
               &_FileMetaDataRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FileMetaDataRequest& a, FileMetaDataRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FileMetaDataRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileMetaDataRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileMetaDataRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileMetaDataRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileMetaDataRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileMetaDataRequest& from) {
    FileMetaDataRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileMetaDataRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "storageserver.FileMetaDataRequest";
  }
  protected:
  explicit FileMetaDataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFullpathFieldNumber = 2,
    kTimestampFieldNumber = 3,
    kIdFieldNumber = 1,
  };
  // string fullpath = 2;
  void clear_fullpath();
  const std::string& fullpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_fullpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_fullpath();
  PROTOBUF_NODISCARD std::string* release_fullpath();
  void set_allocated_fullpath(std::string* fullpath);
  private:
  const std::string& _internal_fullpath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fullpath(const std::string& value);
  std::string* _internal_mutable_fullpath();
  public:

  // string timestamp = 3;
  void clear_timestamp();
  const std::string& timestamp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timestamp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* timestamp);
  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const std::string& value);
  std::string* _internal_mutable_timestamp();
  public:

  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:storageserver.FileMetaDataRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fullpath_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestamp_;
    uint64_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_storageserver_2eproto;
};
// -------------------------------------------------------------------

class FileMetaDataReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:storageserver.FileMetaDataReply) */ {
 public:
  inline FileMetaDataReply() : FileMetaDataReply(nullptr) {}
  ~FileMetaDataReply() override;
  explicit PROTOBUF_CONSTEXPR FileMetaDataReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileMetaDataReply(const FileMetaDataReply& from);
  FileMetaDataReply(FileMetaDataReply&& from) noexcept
    : FileMetaDataReply() {
    *this = ::std::move(from);
  }

  inline FileMetaDataReply& operator=(const FileMetaDataReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileMetaDataReply& operator=(FileMetaDataReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileMetaDataReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileMetaDataReply* internal_default_instance() {
    return reinterpret_cast<const FileMetaDataReply*>(
               &_FileMetaDataReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(FileMetaDataReply& a, FileMetaDataReply& b) {
    a.Swap(&b);
  }
  inline void Swap(FileMetaDataReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileMetaDataReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileMetaDataReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileMetaDataReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileMetaDataReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileMetaDataReply& from) {
    FileMetaDataReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileMetaDataReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "storageserver.FileMetaDataReply";
  }
  protected:
  explicit FileMetaDataReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFullpathFieldNumber = 2,
    kErrorFieldNumber = 3,
    kIdFieldNumber = 1,
  };
  // string fullpath = 2;
  void clear_fullpath();
  const std::string& fullpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_fullpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_fullpath();
  PROTOBUF_NODISCARD std::string* release_fullpath();
  void set_allocated_fullpath(std::string* fullpath);
  private:
  const std::string& _internal_fullpath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fullpath(const std::string& value);
  std::string* _internal_mutable_fullpath();
  public:

  // string error = 3;
  void clear_error();
  const std::string& error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error();
  PROTOBUF_NODISCARD std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:storageserver.FileMetaDataReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fullpath_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
    uint64_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_storageserver_2eproto;
};
// -------------------------------------------------------------------

class FileWriteRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:storageserver.FileWriteRequest) */ {
 public:
  inline FileWriteRequest() : FileWriteRequest(nullptr) {}
  ~FileWriteRequest() override;
  explicit PROTOBUF_CONSTEXPR FileWriteRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileWriteRequest(const FileWriteRequest& from);
  FileWriteRequest(FileWriteRequest&& from) noexcept
    : FileWriteRequest() {
    *this = ::std::move(from);
  }

  inline FileWriteRequest& operator=(const FileWriteRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileWriteRequest& operator=(FileWriteRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileWriteRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileWriteRequest* internal_default_instance() {
    return reinterpret_cast<const FileWriteRequest*>(
               &_FileWriteRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(FileWriteRequest& a, FileWriteRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FileWriteRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileWriteRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileWriteRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileWriteRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileWriteRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileWriteRequest& from) {
    FileWriteRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileWriteRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "storageserver.FileWriteRequest";
  }
  protected:
  explicit FileWriteRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFullpathFieldNumber = 2,
    kPayloadFieldNumber = 5,
    kIdFieldNumber = 1,
    kOffsetFieldNumber = 3,
    kLenFieldNumber = 4,
  };
  // string fullpath = 2;
  void clear_fullpath();
  const std::string& fullpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_fullpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_fullpath();
  PROTOBUF_NODISCARD std::string* release_fullpath();
  void set_allocated_fullpath(std::string* fullpath);
  private:
  const std::string& _internal_fullpath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fullpath(const std::string& value);
  std::string* _internal_mutable_fullpath();
  public:

  // bytes payload = 5;
  void clear_payload();
  const std::string& payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_payload();
  PROTOBUF_NODISCARD std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // uint64 offset = 3;
  void clear_offset();
  uint64_t offset() const;
  void set_offset(uint64_t value);
  private:
  uint64_t _internal_offset() const;
  void _internal_set_offset(uint64_t value);
  public:

  // uint64 len = 4;
  void clear_len();
  uint64_t len() const;
  void set_len(uint64_t value);
  private:
  uint64_t _internal_len() const;
  void _internal_set_len(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:storageserver.FileWriteRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fullpath_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
    uint64_t id_;
    uint64_t offset_;
    uint64_t len_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_storageserver_2eproto;
};
// -------------------------------------------------------------------

class FileWriteReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:storageserver.FileWriteReply) */ {
 public:
  inline FileWriteReply() : FileWriteReply(nullptr) {}
  ~FileWriteReply() override;
  explicit PROTOBUF_CONSTEXPR FileWriteReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileWriteReply(const FileWriteReply& from);
  FileWriteReply(FileWriteReply&& from) noexcept
    : FileWriteReply() {
    *this = ::std::move(from);
  }

  inline FileWriteReply& operator=(const FileWriteReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileWriteReply& operator=(FileWriteReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileWriteReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileWriteReply* internal_default_instance() {
    return reinterpret_cast<const FileWriteReply*>(
               &_FileWriteReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(FileWriteReply& a, FileWriteReply& b) {
    a.Swap(&b);
  }
  inline void Swap(FileWriteReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileWriteReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileWriteReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileWriteReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileWriteReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileWriteReply& from) {
    FileWriteReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileWriteReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "storageserver.FileWriteReply";
  }
  protected:
  explicit FileWriteReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFullpathFieldNumber = 2,
    kErrorFieldNumber = 4,
    kIdFieldNumber = 1,
    kLenFieldNumber = 3,
  };
  // string fullpath = 2;
  void clear_fullpath();
  const std::string& fullpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_fullpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_fullpath();
  PROTOBUF_NODISCARD std::string* release_fullpath();
  void set_allocated_fullpath(std::string* fullpath);
  private:
  const std::string& _internal_fullpath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fullpath(const std::string& value);
  std::string* _internal_mutable_fullpath();
  public:

  // string error = 4;
  void clear_error();
  const std::string& error() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error();
  PROTOBUF_NODISCARD std::string* release_error();
  void set_allocated_error(std::string* error);
  private:
  const std::string& _internal_error() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error(const std::string& value);
  std::string* _internal_mutable_error();
  public:

  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // uint64 len = 3;
  void clear_len();
  uint64_t len() const;
  void set_len(uint64_t value);
  private:
  uint64_t _internal_len() const;
  void _internal_set_len(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:storageserver.FileWriteReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fullpath_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_;
    uint64_t id_;
    uint64_t len_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_storageserver_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HelloRequest

// string name = 1;
inline void HelloRequest::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& HelloRequest::name() const {
  // @@protoc_insertion_point(field_get:storageserver.HelloRequest.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HelloRequest::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:storageserver.HelloRequest.name)
}
inline std::string* HelloRequest::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:storageserver.HelloRequest.name)
  return _s;
}
inline const std::string& HelloRequest::_internal_name() const {
  return _impl_.name_.Get();
}
inline void HelloRequest::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* HelloRequest::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* HelloRequest::release_name() {
  // @@protoc_insertion_point(field_release:storageserver.HelloRequest.name)
  return _impl_.name_.Release();
}
inline void HelloRequest::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:storageserver.HelloRequest.name)
}

// -------------------------------------------------------------------

// HelloReply

// string message = 1;
inline void HelloReply::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& HelloReply::message() const {
  // @@protoc_insertion_point(field_get:storageserver.HelloReply.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HelloReply::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:storageserver.HelloReply.message)
}
inline std::string* HelloReply::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:storageserver.HelloReply.message)
  return _s;
}
inline const std::string& HelloReply::_internal_message() const {
  return _impl_.message_.Get();
}
inline void HelloReply::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* HelloReply::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* HelloReply::release_message() {
  // @@protoc_insertion_point(field_release:storageserver.HelloReply.message)
  return _impl_.message_.Release();
}
inline void HelloReply::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:storageserver.HelloReply.message)
}

// -------------------------------------------------------------------

// FileMetaDataRequest

// uint64 id = 1;
inline void FileMetaDataRequest::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t FileMetaDataRequest::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t FileMetaDataRequest::id() const {
  // @@protoc_insertion_point(field_get:storageserver.FileMetaDataRequest.id)
  return _internal_id();
}
inline void FileMetaDataRequest::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void FileMetaDataRequest::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:storageserver.FileMetaDataRequest.id)
}

// string fullpath = 2;
inline void FileMetaDataRequest::clear_fullpath() {
  _impl_.fullpath_.ClearToEmpty();
}
inline const std::string& FileMetaDataRequest::fullpath() const {
  // @@protoc_insertion_point(field_get:storageserver.FileMetaDataRequest.fullpath)
  return _internal_fullpath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileMetaDataRequest::set_fullpath(ArgT0&& arg0, ArgT... args) {
 
 _impl_.fullpath_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:storageserver.FileMetaDataRequest.fullpath)
}
inline std::string* FileMetaDataRequest::mutable_fullpath() {
  std::string* _s = _internal_mutable_fullpath();
  // @@protoc_insertion_point(field_mutable:storageserver.FileMetaDataRequest.fullpath)
  return _s;
}
inline const std::string& FileMetaDataRequest::_internal_fullpath() const {
  return _impl_.fullpath_.Get();
}
inline void FileMetaDataRequest::_internal_set_fullpath(const std::string& value) {
  
  _impl_.fullpath_.Set(value, GetArenaForAllocation());
}
inline std::string* FileMetaDataRequest::_internal_mutable_fullpath() {
  
  return _impl_.fullpath_.Mutable(GetArenaForAllocation());
}
inline std::string* FileMetaDataRequest::release_fullpath() {
  // @@protoc_insertion_point(field_release:storageserver.FileMetaDataRequest.fullpath)
  return _impl_.fullpath_.Release();
}
inline void FileMetaDataRequest::set_allocated_fullpath(std::string* fullpath) {
  if (fullpath != nullptr) {
    
  } else {
    
  }
  _impl_.fullpath_.SetAllocated(fullpath, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.fullpath_.IsDefault()) {
    _impl_.fullpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:storageserver.FileMetaDataRequest.fullpath)
}

// string timestamp = 3;
inline void FileMetaDataRequest::clear_timestamp() {
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& FileMetaDataRequest::timestamp() const {
  // @@protoc_insertion_point(field_get:storageserver.FileMetaDataRequest.timestamp)
  return _internal_timestamp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileMetaDataRequest::set_timestamp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timestamp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:storageserver.FileMetaDataRequest.timestamp)
}
inline std::string* FileMetaDataRequest::mutable_timestamp() {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:storageserver.FileMetaDataRequest.timestamp)
  return _s;
}
inline const std::string& FileMetaDataRequest::_internal_timestamp() const {
  return _impl_.timestamp_.Get();
}
inline void FileMetaDataRequest::_internal_set_timestamp(const std::string& value) {
  
  _impl_.timestamp_.Set(value, GetArenaForAllocation());
}
inline std::string* FileMetaDataRequest::_internal_mutable_timestamp() {
  
  return _impl_.timestamp_.Mutable(GetArenaForAllocation());
}
inline std::string* FileMetaDataRequest::release_timestamp() {
  // @@protoc_insertion_point(field_release:storageserver.FileMetaDataRequest.timestamp)
  return _impl_.timestamp_.Release();
}
inline void FileMetaDataRequest::set_allocated_timestamp(std::string* timestamp) {
  if (timestamp != nullptr) {
    
  } else {
    
  }
  _impl_.timestamp_.SetAllocated(timestamp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:storageserver.FileMetaDataRequest.timestamp)
}

// -------------------------------------------------------------------

// FileMetaDataReply

// uint64 id = 1;
inline void FileMetaDataReply::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t FileMetaDataReply::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t FileMetaDataReply::id() const {
  // @@protoc_insertion_point(field_get:storageserver.FileMetaDataReply.id)
  return _internal_id();
}
inline void FileMetaDataReply::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void FileMetaDataReply::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:storageserver.FileMetaDataReply.id)
}

// string fullpath = 2;
inline void FileMetaDataReply::clear_fullpath() {
  _impl_.fullpath_.ClearToEmpty();
}
inline const std::string& FileMetaDataReply::fullpath() const {
  // @@protoc_insertion_point(field_get:storageserver.FileMetaDataReply.fullpath)
  return _internal_fullpath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileMetaDataReply::set_fullpath(ArgT0&& arg0, ArgT... args) {
 
 _impl_.fullpath_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:storageserver.FileMetaDataReply.fullpath)
}
inline std::string* FileMetaDataReply::mutable_fullpath() {
  std::string* _s = _internal_mutable_fullpath();
  // @@protoc_insertion_point(field_mutable:storageserver.FileMetaDataReply.fullpath)
  return _s;
}
inline const std::string& FileMetaDataReply::_internal_fullpath() const {
  return _impl_.fullpath_.Get();
}
inline void FileMetaDataReply::_internal_set_fullpath(const std::string& value) {
  
  _impl_.fullpath_.Set(value, GetArenaForAllocation());
}
inline std::string* FileMetaDataReply::_internal_mutable_fullpath() {
  
  return _impl_.fullpath_.Mutable(GetArenaForAllocation());
}
inline std::string* FileMetaDataReply::release_fullpath() {
  // @@protoc_insertion_point(field_release:storageserver.FileMetaDataReply.fullpath)
  return _impl_.fullpath_.Release();
}
inline void FileMetaDataReply::set_allocated_fullpath(std::string* fullpath) {
  if (fullpath != nullptr) {
    
  } else {
    
  }
  _impl_.fullpath_.SetAllocated(fullpath, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.fullpath_.IsDefault()) {
    _impl_.fullpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:storageserver.FileMetaDataReply.fullpath)
}

// string error = 3;
inline void FileMetaDataReply::clear_error() {
  _impl_.error_.ClearToEmpty();
}
inline const std::string& FileMetaDataReply::error() const {
  // @@protoc_insertion_point(field_get:storageserver.FileMetaDataReply.error)
  return _internal_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileMetaDataReply::set_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:storageserver.FileMetaDataReply.error)
}
inline std::string* FileMetaDataReply::mutable_error() {
  std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:storageserver.FileMetaDataReply.error)
  return _s;
}
inline const std::string& FileMetaDataReply::_internal_error() const {
  return _impl_.error_.Get();
}
inline void FileMetaDataReply::_internal_set_error(const std::string& value) {
  
  _impl_.error_.Set(value, GetArenaForAllocation());
}
inline std::string* FileMetaDataReply::_internal_mutable_error() {
  
  return _impl_.error_.Mutable(GetArenaForAllocation());
}
inline std::string* FileMetaDataReply::release_error() {
  // @@protoc_insertion_point(field_release:storageserver.FileMetaDataReply.error)
  return _impl_.error_.Release();
}
inline void FileMetaDataReply::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  _impl_.error_.SetAllocated(error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:storageserver.FileMetaDataReply.error)
}

// -------------------------------------------------------------------

// FileWriteRequest

// uint64 id = 1;
inline void FileWriteRequest::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t FileWriteRequest::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t FileWriteRequest::id() const {
  // @@protoc_insertion_point(field_get:storageserver.FileWriteRequest.id)
  return _internal_id();
}
inline void FileWriteRequest::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void FileWriteRequest::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:storageserver.FileWriteRequest.id)
}

// string fullpath = 2;
inline void FileWriteRequest::clear_fullpath() {
  _impl_.fullpath_.ClearToEmpty();
}
inline const std::string& FileWriteRequest::fullpath() const {
  // @@protoc_insertion_point(field_get:storageserver.FileWriteRequest.fullpath)
  return _internal_fullpath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileWriteRequest::set_fullpath(ArgT0&& arg0, ArgT... args) {
 
 _impl_.fullpath_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:storageserver.FileWriteRequest.fullpath)
}
inline std::string* FileWriteRequest::mutable_fullpath() {
  std::string* _s = _internal_mutable_fullpath();
  // @@protoc_insertion_point(field_mutable:storageserver.FileWriteRequest.fullpath)
  return _s;
}
inline const std::string& FileWriteRequest::_internal_fullpath() const {
  return _impl_.fullpath_.Get();
}
inline void FileWriteRequest::_internal_set_fullpath(const std::string& value) {
  
  _impl_.fullpath_.Set(value, GetArenaForAllocation());
}
inline std::string* FileWriteRequest::_internal_mutable_fullpath() {
  
  return _impl_.fullpath_.Mutable(GetArenaForAllocation());
}
inline std::string* FileWriteRequest::release_fullpath() {
  // @@protoc_insertion_point(field_release:storageserver.FileWriteRequest.fullpath)
  return _impl_.fullpath_.Release();
}
inline void FileWriteRequest::set_allocated_fullpath(std::string* fullpath) {
  if (fullpath != nullptr) {
    
  } else {
    
  }
  _impl_.fullpath_.SetAllocated(fullpath, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.fullpath_.IsDefault()) {
    _impl_.fullpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:storageserver.FileWriteRequest.fullpath)
}

// uint64 offset = 3;
inline void FileWriteRequest::clear_offset() {
  _impl_.offset_ = uint64_t{0u};
}
inline uint64_t FileWriteRequest::_internal_offset() const {
  return _impl_.offset_;
}
inline uint64_t FileWriteRequest::offset() const {
  // @@protoc_insertion_point(field_get:storageserver.FileWriteRequest.offset)
  return _internal_offset();
}
inline void FileWriteRequest::_internal_set_offset(uint64_t value) {
  
  _impl_.offset_ = value;
}
inline void FileWriteRequest::set_offset(uint64_t value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:storageserver.FileWriteRequest.offset)
}

// uint64 len = 4;
inline void FileWriteRequest::clear_len() {
  _impl_.len_ = uint64_t{0u};
}
inline uint64_t FileWriteRequest::_internal_len() const {
  return _impl_.len_;
}
inline uint64_t FileWriteRequest::len() const {
  // @@protoc_insertion_point(field_get:storageserver.FileWriteRequest.len)
  return _internal_len();
}
inline void FileWriteRequest::_internal_set_len(uint64_t value) {
  
  _impl_.len_ = value;
}
inline void FileWriteRequest::set_len(uint64_t value) {
  _internal_set_len(value);
  // @@protoc_insertion_point(field_set:storageserver.FileWriteRequest.len)
}

// bytes payload = 5;
inline void FileWriteRequest::clear_payload() {
  _impl_.payload_.ClearToEmpty();
}
inline const std::string& FileWriteRequest::payload() const {
  // @@protoc_insertion_point(field_get:storageserver.FileWriteRequest.payload)
  return _internal_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileWriteRequest::set_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.payload_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:storageserver.FileWriteRequest.payload)
}
inline std::string* FileWriteRequest::mutable_payload() {
  std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:storageserver.FileWriteRequest.payload)
  return _s;
}
inline const std::string& FileWriteRequest::_internal_payload() const {
  return _impl_.payload_.Get();
}
inline void FileWriteRequest::_internal_set_payload(const std::string& value) {
  
  _impl_.payload_.Set(value, GetArenaForAllocation());
}
inline std::string* FileWriteRequest::_internal_mutable_payload() {
  
  return _impl_.payload_.Mutable(GetArenaForAllocation());
}
inline std::string* FileWriteRequest::release_payload() {
  // @@protoc_insertion_point(field_release:storageserver.FileWriteRequest.payload)
  return _impl_.payload_.Release();
}
inline void FileWriteRequest::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  _impl_.payload_.SetAllocated(payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:storageserver.FileWriteRequest.payload)
}

// -------------------------------------------------------------------

// FileWriteReply

// uint64 id = 1;
inline void FileWriteReply::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t FileWriteReply::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t FileWriteReply::id() const {
  // @@protoc_insertion_point(field_get:storageserver.FileWriteReply.id)
  return _internal_id();
}
inline void FileWriteReply::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void FileWriteReply::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:storageserver.FileWriteReply.id)
}

// string fullpath = 2;
inline void FileWriteReply::clear_fullpath() {
  _impl_.fullpath_.ClearToEmpty();
}
inline const std::string& FileWriteReply::fullpath() const {
  // @@protoc_insertion_point(field_get:storageserver.FileWriteReply.fullpath)
  return _internal_fullpath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileWriteReply::set_fullpath(ArgT0&& arg0, ArgT... args) {
 
 _impl_.fullpath_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:storageserver.FileWriteReply.fullpath)
}
inline std::string* FileWriteReply::mutable_fullpath() {
  std::string* _s = _internal_mutable_fullpath();
  // @@protoc_insertion_point(field_mutable:storageserver.FileWriteReply.fullpath)
  return _s;
}
inline const std::string& FileWriteReply::_internal_fullpath() const {
  return _impl_.fullpath_.Get();
}
inline void FileWriteReply::_internal_set_fullpath(const std::string& value) {
  
  _impl_.fullpath_.Set(value, GetArenaForAllocation());
}
inline std::string* FileWriteReply::_internal_mutable_fullpath() {
  
  return _impl_.fullpath_.Mutable(GetArenaForAllocation());
}
inline std::string* FileWriteReply::release_fullpath() {
  // @@protoc_insertion_point(field_release:storageserver.FileWriteReply.fullpath)
  return _impl_.fullpath_.Release();
}
inline void FileWriteReply::set_allocated_fullpath(std::string* fullpath) {
  if (fullpath != nullptr) {
    
  } else {
    
  }
  _impl_.fullpath_.SetAllocated(fullpath, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.fullpath_.IsDefault()) {
    _impl_.fullpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:storageserver.FileWriteReply.fullpath)
}

// uint64 len = 3;
inline void FileWriteReply::clear_len() {
  _impl_.len_ = uint64_t{0u};
}
inline uint64_t FileWriteReply::_internal_len() const {
  return _impl_.len_;
}
inline uint64_t FileWriteReply::len() const {
  // @@protoc_insertion_point(field_get:storageserver.FileWriteReply.len)
  return _internal_len();
}
inline void FileWriteReply::_internal_set_len(uint64_t value) {
  
  _impl_.len_ = value;
}
inline void FileWriteReply::set_len(uint64_t value) {
  _internal_set_len(value);
  // @@protoc_insertion_point(field_set:storageserver.FileWriteReply.len)
}

// string error = 4;
inline void FileWriteReply::clear_error() {
  _impl_.error_.ClearToEmpty();
}
inline const std::string& FileWriteReply::error() const {
  // @@protoc_insertion_point(field_get:storageserver.FileWriteReply.error)
  return _internal_error();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileWriteReply::set_error(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:storageserver.FileWriteReply.error)
}
inline std::string* FileWriteReply::mutable_error() {
  std::string* _s = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:storageserver.FileWriteReply.error)
  return _s;
}
inline const std::string& FileWriteReply::_internal_error() const {
  return _impl_.error_.Get();
}
inline void FileWriteReply::_internal_set_error(const std::string& value) {
  
  _impl_.error_.Set(value, GetArenaForAllocation());
}
inline std::string* FileWriteReply::_internal_mutable_error() {
  
  return _impl_.error_.Mutable(GetArenaForAllocation());
}
inline std::string* FileWriteReply::release_error() {
  // @@protoc_insertion_point(field_release:storageserver.FileWriteReply.error)
  return _impl_.error_.Release();
}
inline void FileWriteReply::set_allocated_error(std::string* error) {
  if (error != nullptr) {
    
  } else {
    
  }
  _impl_.error_.SetAllocated(error, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_.IsDefault()) {
    _impl_.error_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:storageserver.FileWriteReply.error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace storageserver

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_storageserver_2eproto
